name: Upload to Mega

on:
  schedule:
    - cron: "30 19 1 */1 *" #set to run 30 min after scrape action starts

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3

      - name: Upload 
        uses: Difegue/action-megacmd@master
        with:
          args: put ./data/* /Rankings
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
